CREATE TABLE `bounty_comments` (
	`id` text PRIMARY KEY NOT NULL,
	`bounty_id` text NOT NULL,
	`author_id` text NOT NULL,
	`content` text NOT NULL,
	`parent_id` text,
	`is_internal` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`bounty_id`) REFERENCES `innovation_bounties`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`parent_id`) REFERENCES `bounty_comments`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `bounty_proposals` (
	`id` text PRIMARY KEY NOT NULL,
	`bounty_id` text NOT NULL,
	`project_id` text,
	`proposer_id` text NOT NULL,
	`proposal_title` text NOT NULL,
	`proposal_description` text NOT NULL,
	`approach` text NOT NULL,
	`timeline` text,
	`budget` text,
	`team_members` text,
	`status` text DEFAULT 'submitted',
	`review_notes` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`bounty_id`) REFERENCES `innovation_bounties`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`proposer_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `innovation_bounties` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_name` text NOT NULL,
	`organization_type` text NOT NULL,
	`organization_contact` text,
	`organization_website` text,
	`title` text NOT NULL,
	`problem_statement` text NOT NULL,
	`use_case` text NOT NULL,
	`current_state` text,
	`common_tools_used` text,
	`desired_outcome` text NOT NULL,
	`technical_requirements` text,
	`constraints` text,
	`deliverables` text,
	`bounty_amount` integer,
	`bounty_type` text DEFAULT 'fixed',
	`deadline` text,
	`category` text,
	`tags` text,
	`status` text DEFAULT 'draft',
	`screening_notes` text,
	`screened_by` text,
	`screened_at` text,
	`published_at` text,
	`submitter_id` text NOT NULL,
	`is_anonymous` integer DEFAULT 0 NOT NULL,
	`view_count` integer DEFAULT 0 NOT NULL,
	`proposal_count` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`screened_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`submitter_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
