/**
 * Utility functions for user onboarding detection
 */

/**
 * Checks if a username appears to be auto-generated
 * Auto-generated usernames follow the pattern: "user_[8 chars]"
 */
export function isAutoGeneratedUsername(username: string | null | undefined): boolean {
  if (!username) return true;

  // Check for pattern like "user_abc12345" (auto-generated with random hash)
  const autoGenPattern = /^user_[a-z0-9]{8}$/i;
  return autoGenPattern.test(username);
}

/**
 * Determines if a user needs to complete onboarding
 * A user needs onboarding if:
 * - They have no username (null)
 * - They have an auto-generated username
 */
export function needsOnboarding(username: string | null | undefined): boolean {
  return !username || isAutoGeneratedUsername(username);
}

/**
 * Validates username format
 * Requirements:
 * - 3-30 characters
 * - Letters, numbers, underscores, hyphens only
 * - Must start with a letter or number
 */
export function validateUsernameFormat(username: string): { valid: boolean; error?: string } {
  if (!username || username.trim().length === 0) {
    return { valid: false, error: "Username is required" };
  }

  const trimmed = username.trim();

  if (trimmed.length < 3) {
    return { valid: false, error: "Username must be at least 3 characters" };
  }

  if (trimmed.length > 30) {
    return { valid: false, error: "Username must be less than 30 characters" };
  }

  // Must start with letter or number, can contain letters, numbers, underscores, hyphens
  const validPattern = /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/;
  if (!validPattern.test(trimmed)) {
    return {
      valid: false,
      error: "Username must start with a letter or number and contain only letters, numbers, underscores, or hyphens"
    };
  }

  // Check if it looks auto-generated (warn user)
  if (isAutoGeneratedUsername(trimmed)) {
    return {
      valid: false,
      error: "Please choose a unique username instead of the auto-generated format"
    };
  }

  return { valid: true };
}
